# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test

production:
  pool: 10
  reaping_frequency: 10
  reconnect: true
  url: <%= ENV['APPSDECK_POSTGRESQL_URL'] %>
